#######################################################################################################
#  ███    ██  █████  ████████       ██     ██ ██   ██ ██ ████████ ███████ ██      ██ ███████ ████████ #
#  ████   ██ ██   ██    ██          ██     ██ ██   ██ ██    ██    ██      ██      ██ ██         ██    #
#  ██ ██  ██ ███████    ██    █████ ██  █  ██ ███████ ██    ██    █████   ██      ██ ███████    ██    #
#  ██  ██ ██ ██   ██    ██          ██ ███ ██ ██   ██ ██    ██    ██      ██      ██      ██    ██    #
#  ██   ████ ██   ██    ██           ███ ███  ██   ██ ██    ██    ███████ ███████ ██ ███████    ██    #
#######################################################################################################
# Made by Nat0uille & Love                                                                            #
# Config version : 1.4                                                                                #
#######################################################################################################
# All texts use the MiniMessage format. If you use anything else, it will not work!!!                 #
# To create your messages, you can use the website https://webui.advntr.dev/                          #
#######################################################################################################
# SETTINGS                                                                                            #
#######################################################################################################
# Language of the plugin (en-us / fr-fr)
lang: en-us

database:
  # Format: MySQL / SQLite
  type: "SQLite"
  # For MySQL, fill in the following fields
  host: "localhost"
  port: 3306
  database: "nat_whitelist"
  username: ""
  password: ""

# If true, the whitelist is enabled.
enabled: true
# If true, the player will be kicked when he is not whitelisted. If false, the player will be able to join.
kicknowhitelisted: true
# Discord webhook URL. If no URL is specified, the plugin will not send messages to Discord.
discord-webhook-url: ""